import type { OperatorControlSnapshot } from "../../../domain/index.js";
import { fallbackSnapshotNow as now } from "../shared.js";

export const fallbackOperatorControlTasks: OperatorControlSnapshot["tasks"] = {
  summary: {
    accepted: 1,
    queued: 2,
    started: 1,
    retrying: 0,
    blocked: 1,
    completed: 8,
    "dead-letter": 1,
  },
  tasks: [
    {
      envelope: {
        task_id: "task-operator-1",
        requester: { id: "tonya", kind: "operator" },
        target: { capability: "backend", alias: "raekwon" },
        objective: "Verify operator task lifecycle",
        tier: "STANDARD",
        acceptance_criteria: ["task store contains completed task"],
        timeout_s: 900,
      },
      receipt: {
        task_id: "task-operator-1",
        run_id: "task-run-1",
        state: "completed",
        owner: "2tony",
        attempt: 0,
        created_at: now - 30 * 60_000,
        updated_at: now - 5 * 60_000,
        queue_latency_ms: 2400,
        artifacts: ["task://task-operator-1"],
        failure_code: null,
      },
      events: [],
      validation: {
        validation_id: "val-operator-1",
        validator: "northstar",
        result: "passed",
      },
      outcome: {
        outcome: "success",
        verification_status: "passed",
        rework_needed: false,
        recorded_at: now - 5 * 60_000,
      },
    },
    {
      envelope: {
        task_id: "task-rollout-2",
        parent_task_id: "task-operator-1",
        requester: { id: "tonya", kind: "operator" },
        target: {
          capability: "infra",
          alias: "ghostface",
          team_id: "execution-fleet",
        },
        objective: "Reconcile AKS operator deploy drift",
        tier: "HEAVY",
        acceptance_criteria: ["pods healthy", "receipts emitted"],
        timeout_s: 1800,
      },
      receipt: {
        task_id: "task-rollout-2",
        run_id: "task-run-2",
        state: "blocked",
        owner: "2tony",
        attempt: 1,
        created_at: now - 55 * 60_000,
        updated_at: now - 9 * 60_000,
        queue_latency_ms: 6200,
        artifacts: [],
        failure_code: "approval-pending",
      },
      events: [],
      validation: null,
      outcome: null,
    },
    {
      envelope: {
        task_id: "task-memory-3",
        parent_task_id: "task-rollout-2",
        requester: { id: "tonya", kind: "operator" },
        target: {
          capability: "analysis",
          alias: "gza",
          team_id: "execution-fleet",
        },
        objective: "Promote verified task outcomes into shared memory",
        tier: "LITE",
        acceptance_criteria: ["fresh memory collections visible"],
        timeout_s: 300,
      },
      receipt: {
        task_id: "task-memory-3",
        run_id: "task-run-3",
        state: "queued",
        owner: "tonya",
        attempt: 0,
        created_at: now - 8 * 60_000,
        updated_at: now - 2 * 60_000,
        queue_latency_ms: 180,
        artifacts: [],
        failure_code: null,
      },
      events: [],
      validation: null,
      outcome: null,
    },
  ],
};
