import type { OperatorControlSnapshot } from "../../../domain/index.js";
import { OPERATOR_DISPATCH_ENDPOINTS } from "../../../paths.js";
import { fallbackSnapshotNow as now } from "../shared.js";
import { agentDefaults, k8sDefaults, teamDefaults } from "./defaults.js";

export const fallbackOperatorControlRegistryDetail = {
  schema: "OperatorAgentRegistryV1",
  generatedAt: now - 8 * 60_000,
  sourcePath:
    "/workspace/projects/openclaw/src/caviclaw/operator-control/agents.yaml",
  sourceHash: "mock-registry-hash",
  agentCount: 22,
  teamCount: 5,
  operatorRuntime: {
    transports: {
      delegatedHttp: { globalDefaultAlias: "tonys-angels" },
    },
  },
  skillOwnership: [],
  agents: [
    {
      ...agentDefaults,
      id: "raekwon",
      name: "Raekwon the Chef",
      role: "Backend - Express 5, Prisma 7, PostgreSQL",
      specialty: "Backend - Express 5, Prisma 7, PostgreSQL",
      model: "openai-codex/gpt-5.3-codex",
      skill: "/workspace/skills/raekwon/SKILL.md",
      spawnTemplate:
        "/teams/development/workspace-development/dispatch/spawn-templates/raekwon.md",
      repos: ["bt-client-backend"],
      triggers: ["backend", "api"],
      notes: "Single-service backend specialist.",
      teams: ["execution-fleet"],
      maxConcurrentSessions: 1,
      capabilities: ["backend", "api implementation"],
      mcpAccess: ["postgres"],
      reviewHandles: ["backend"],
    },
    {
      ...agentDefaults,
      id: "ghostface",
      name: "Ghostface Killah",
      role: "DevOps - K8s, Azure, Docker, GitHub Actions",
      specialty: "DevOps - K8s, Azure, Docker, GitHub Actions",
      model: "openai-codex/gpt-5.3-codex",
      skill: "/workspace/skills/ghostface/SKILL.md",
      spawnTemplate:
        "/teams/development/workspace-development/dispatch/spawn-templates/ghostface.md",
      repos: ["bt-k8s"],
      triggers: ["kubernetes", "aks"],
      notes: "Infra and rollout specialist.",
      teams: ["execution-fleet"],
      maxConcurrentSessions: 1,
    },
    {
      ...agentDefaults,
      id: "deb",
      name: "Deb",
      role: "GitHub Projects kanban operator",
      specialty: "GitHub Projects kanban operator",
      model: "openai-codex/gpt-5.3-codex",
      skill: "/workspace/skills/deb/SKILL.md",
      spawnTemplate:
        "/teams/project-ops/workspace-project-ops/dispatch/spawn-templates/deb.md",
      repos: ["all"],
      triggers: ["kanban", "board"],
      notes: "Project board operator.",
      teams: ["project-ops"],
      maxConcurrentSessions: 1,
    },
    {
      ...agentDefaults,
      id: "tonys-angels",
      name: "Tony's Angels",
      role: "Marketing orchestrator",
      specialty: "Marketing - campaigns, content, growth, investor narrative",
      model: "anthropic/claude-opus-4-6",
      skill: "/workspace/skills/tonys-angels/SKILL.md",
      spawnTemplate: null,
      repos: ["none"],
      triggers: ["marketing", "campaign"],
      notes: "Marketing domain orchestrator.",
      teams: ["marketing"],
      maxConcurrentSessions: 1,
      capabilities: [
        "campaign orchestration",
        "cross-channel planning",
        "delegation",
      ],
      mcpAccess: ["linkedin", "instagram", "twitter"],
      reviewHandles: ["marketing", "campaigns"],
    },
    {
      ...agentDefaults,
      id: "story-architect",
      name: "Story Architect",
      role: "Narrative strategy specialist",
      specialty: "Narrative systems, positioning, and campaign story arcs",
      model: "openai/gpt-5.4",
      skill: "/workspace/skills/story-architect/SKILL.md",
      spawnTemplate: null,
      repos: ["none"],
      triggers: ["story", "narrative", "linkedin"],
      notes: "Builds narrative structure and channel-specific story variants.",
      teams: ["marketing"],
      maxConcurrentSessions: 1,
      capabilities: ["positioning", "storytelling", "campaign strategy"],
      mcpAccess: ["linkedin", "notion"],
      reviewHandles: ["narrative"],
    },
    {
      ...agentDefaults,
      id: "copywriting-ninja",
      name: "Copywriting Ninja",
      role: "High-conversion copy specialist",
      specialty:
        "Hooks, CTAs, paid/organic copy packs, and lifecycle messaging",
      model: "openai/gpt-5.4",
      skill: "/workspace/skills/copywriting-ninja/SKILL.md",
      spawnTemplate: null,
      repos: ["none"],
      triggers: ["copy", "cta", "instagram", "twitter"],
      notes: "Owns short-form and conversion-focused messaging variants.",
      teams: ["marketing"],
      maxConcurrentSessions: 1,
      capabilities: [
        "copywriting",
        "conversion optimization",
        "social content",
      ],
      mcpAccess: ["instagram", "twitter"],
      reviewHandles: ["copy"],
    },
    {
      ...agentDefaults,
      id: "investor-deck-architect",
      name: "Investor Deck Architect",
      role: "Investor narrative and deck specialist",
      specialty:
        "Fundraising narrative, KPI storytelling, and board-ready decks",
      model: "openai/gpt-5.4",
      skill: "/workspace/skills/investor-deck-architect/SKILL.md",
      spawnTemplate: null,
      repos: ["none"],
      triggers: ["investor", "deck", "fundraising"],
      notes: "Transforms campaign outcomes into investor-facing narratives.",
      teams: ["marketing"],
      maxConcurrentSessions: 1,
      capabilities: [
        "investor narrative",
        "deck architecture",
        "market analysis",
      ],
      mcpAccess: ["google-slides", "notion"],
      reviewHandles: ["investor"],
    },
    {
      ...agentDefaults,
      id: "scout",
      name: "Scout",
      role: "Research lead",
      specialty:
        "Research operations — filesystem cartography, git-aware project indexing, multi-provider web retrieval, and upstream OpenClaw watch synthesis",
      model: null,
      skill: "/teams/research/workspace-research/skills/scout/SKILL.md",
      spawnTemplate:
        "/teams/research/workspace-research/dispatch/spawn-templates/scout.md",
      repos: ["all (read-only recon scope)"],
      triggers: [
        "scout",
        "scout school",
        "reconnaissance",
        "evidence retrieval",
        "where is this file",
        "what changed in this repo",
        "current market check",
        "source discovery",
        "doc discovery",
        "web search",
        "web fetch",
        "upstream openclaw changes",
        "verify current state",
      ],
      notes:
        "Mandatory output contract: /teams/research/workspace-research/skills/scout/references/scout-response-contract.md (SCOUT_RESPONSE_V1). Scout is the only public research entrypoint; all specialist routing stays inside Scout School at /teams/research/workspace-research/agents/research-runtimes.json Scout may self-shard into same-agent worker lanes for broad repo/web retrieval, keeps private persistent state under /teams/research/workspace-research/state, and ordinary lookups stay ephemeral unless an explicit publish gate promotes a completed artifact into shared research. Active Scout School web stack is Brave + Perplexity + Grok/xAI + Exa + Firecrawl, with Reddit/X signal lanes and Playwright escalation.",
      teams: ["control-plane", "research"],
      maxConcurrentSessions: 1,
      capabilities: [
        "reconnaissance",
        "file location intelligence",
        "git-aware project indexing",
        "current-state evidence retrieval",
        "source discovery",
        "docs discovery",
        "multi-provider web discovery",
        "community signal retrieval",
        "deep scrape fallback",
        "web search",
      ],
      mcpAccess: [
        "context7",
        "firecrawl",
        "perplexity",
        "reddit",
        "exa",
        "twitter",
        "playwright",
        "web fetch",
        "upstream change watch",
      ],
      reviewHandles: ["research"],
    },
    {
      ...agentDefaults,
      id: "sproket",
      name: "Sproket",
      role: "Filesystem cartographer",
      specialty:
        "Filesystem — path discovery, repo-shape mapping, git-aware search, cross-root optimization",
      model: null,
      skill: "/teams/research/workspace-research/skills/sproket/SKILL.md",
      spawnTemplate:
        "/teams/research/workspace-research/dispatch/spawn-templates/sproket.md",
      repos: ["none"],
      triggers: ["filesystem", "path", "repo map", "file search"],
      notes: "Internal Scout specialist. Maps filesystem structure and performs targeted path discovery.",
      teams: ["research"],
      maxConcurrentSessions: 1,
      capabilities: ["filesystem search", "path discovery", "repo mapping", "git-aware search"],
      mcpAccess: [],
      reviewHandles: [],
    },
    {
      ...agentDefaults,
      id: "marlin",
      name: "Marlin",
      role: "Web discovery master",
      specialty:
        "Web search — multi-provider search, query formulation, source verification",
      model: null,
      skill: "/teams/research/workspace-research/skills/marlin/SKILL.md",
      spawnTemplate:
        "/teams/research/workspace-research/dispatch/spawn-templates/marlin.md",
      repos: ["none"],
      triggers: ["web search", "search", "query", "source"],
      notes:
        "Internal Scout specialist. Executes web searches with source verification across Brave, Perplexity, Grok/xAI, Exa, Firecrawl, and community-signal lanes such as Reddit and X/Twitter.",
      teams: ["research"],
      maxConcurrentSessions: 1,
      capabilities: [
        "web search",
        "query formulation",
        "source verification",
        "multi-provider search",
        "community signal research",
        "deep scrape fallback",
      ],
      mcpAccess: ["context7", "firecrawl", "perplexity", "reddit", "exa", "twitter", "playwright"],
      reviewHandles: [],
    },
    {
      ...agentDefaults,
      id: "gill",
      name: "Gill",
      role: "Upstream watcher",
      specialty:
        "Upstream — OpenClaw releases, changelog drift, PR movement, adoption packets",
      model: null,
      skill: "/teams/research/workspace-research/skills/gill/SKILL.md",
      spawnTemplate:
        "/teams/research/workspace-research/dispatch/spawn-templates/gill.md",
      repos: ["none"],
      triggers: ["upstream", "changelog", "release", "pr movement"],
      notes: "Internal Scout specialist. Monitors upstream OpenClaw changes and drift.",
      teams: ["research"],
      maxConcurrentSessions: 1,
      capabilities: ["upstream watching", "changelog drift", "pr movement", "adoption packets"],
      mcpAccess: [],
      reviewHandles: [],
    },
  ],
  teams: [
    {
      ...teamDefaults,
      id: "control-plane",
      name: "Control Plane",
      kind: "operator-control",
      parentTeamId: null,
      lead: "tonya",
      leadKind: "runtime",
      routeViaLead: false,
      mission: "Own orchestration, routing, and shared-memory policy.",
      members: ["bobby-digital", "scout"],
      runtimeIds: ["tonya", "qdrant"],
      memberIdentityIds: ["bobby-digital", "scout", "tonya", "qdrant"],
      ownsCapabilities: ["orchestration", "routing", "shared memory"],
      maxParallel: null,
      dispatchTransport: "manual",
      dispatchEndpointEnv: null,
      dispatchPath: null,
      dispatchAuthScheme: null,
      dispatchAuthEnv: null,
      dispatchDefaultAlias: null,
      routingPolicy: "Tonya is authoritative.",
      notes: "Top-level operator governance team.",
      ancestorTeamIds: [],
      descendantTeamIds: [],
    },
    {
      ...teamDefaults,
      id: "execution-fleet",
      name: "Execution Fleet",
      kind: "worker-execution",
      parentTeamId: null,
      lead: "2tony",
      leadKind: "runtime",
      routeViaLead: true,
      mission: "Run engineering and infra execution work.",
      members: ["raekwon", "method-man", "ghostface", "northstar"],
      runtimeIds: ["2tony"],
      memberIdentityIds: [
        "raekwon",
        "method-man",
        "ghostface",
        "northstar",
        "2tony",
      ],
      ownsCapabilities: ["engineering", "infrastructure", "validation"],
      maxParallel: null,
      dispatchTransport: "2tony-http",
      dispatchEndpointEnv: "CAVI_CONTROL_2TONY_URL",
      dispatchPath: "/task",
      dispatchAuthScheme: "bearer",
      dispatchAuthEnv: "CAVI_CONTROL_2TONY_SHARED_SECRET",
      dispatchDefaultAlias: null,
      routingPolicy: "Tonya dispatches; specialists execute.",
      notes: "Scale this by adding worker-safe specialists.",
      ancestorTeamIds: [],
      descendantTeamIds: [],
    },
    {
      ...teamDefaults,
      id: "project-ops",
      name: "Project Ops",
      kind: "planning-governance",
      parentTeamId: null,
      lead: "deb-pod",
      leadKind: "runtime",
      routeViaLead: false,
      mission: "Maintain sprint truth and blocker visibility.",
      members: ["deb"],
      runtimeIds: ["deb-pod"],
      memberIdentityIds: ["deb", "deb-pod"],
      ownsCapabilities: ["sprint management", "backlog hygiene"],
      maxParallel: null,
      dispatchTransport: "deb-http",
      dispatchEndpointEnv: "CAVI_CONTROL_DEB_URL",
      dispatchPath: "/update",
      dispatchAuthScheme: "bearer",
      dispatchAuthEnv: "CAVI_CONTROL_DEB_SHARED_SECRET",
      dispatchDefaultAlias: null,
      routingPolicy: "Deb is governance, not a general worker.",
      notes: "Board system of record.",
      ancestorTeamIds: [],
      descendantTeamIds: [],
    },
    {
      ...teamDefaults,
      id: "marketing",
      name: "Marketing",
      kind: "domain-fleet",
      parentTeamId: null,
      lead: "angela",
      leadKind: "runtime",
      routeViaLead: true,
      mission: "Own campaign and investor narrative workflows.",
      members: [
        "tonys-angels",
        "story-architect",
        "copywriting-ninja",
        "investor-deck-architect",
      ],
      runtimeIds: ["angela"],
      memberIdentityIds: [
        "tonys-angels",
        "story-architect",
        "copywriting-ninja",
        "investor-deck-architect",
        "angela",
      ],
      ownsCapabilities: [
        "marketing",
        "campaign orchestration",
        "investor narrative",
      ],
      maxParallel: null,
      dispatchTransport: "angela-http",
      dispatchEndpointEnv: "CAVI_CONTROL_ANGELA_URL",
      dispatchPath: OPERATOR_DISPATCH_ENDPOINTS.message,
      dispatchAuthScheme: "bearer",
      dispatchAuthEnv: "CAVI_CONTROL_ANGELA_SHARED_SECRET",
      dispatchDefaultAlias: "tonys-angels",
      routingPolicy: "Angela contains the domain boundary.",
      notes: "Separate from engineering and project ops.",
      ancestorTeamIds: [],
      descendantTeamIds: [],
    },
    {
      ...teamDefaults,
      id: "research",
      name: "Scout Research",
      kind: "domain-fleet",
      parentTeamId: null,
      lead: "scout",
      leadKind: "agent",
      routeViaLead: true,
      mission:
        "Route filesystem intelligence, current-state checks, bounded web research, and upstream OpenClaw watch through Scout.",
      members: ["scout", "sproket", "marlin", "gill"],
      runtimeIds: ["tonya"],
      memberIdentityIds: [
        "scout",
        "sproket",
        "marlin",
        "gill",
        "tonya",
      ],
      ownsCapabilities: [
        "reconnaissance",
        "file location intelligence",
        "git-aware project indexing",
        "evidence retrieval",
        "web search",
        "web fetch",
        "current-state verification",
        "source discovery",
      ],
      maxParallel: null,
      dispatchTransport: "delegated-http",
      dispatchEndpointEnv: "CAVI_CONTROL_INTERNAL_CONTROL_URL",
      dispatchPath: OPERATOR_DISPATCH_ENDPOINTS.message,
      dispatchAuthScheme: "bearer",
      dispatchAuthEnv: "CAVI_CONTROL_INTERNAL_CONTROL_SHARED_SECRET",
      dispatchDefaultAlias: "scout",
      routingPolicy: "scout lead-routed",
      notes: "Scout is a first-class research lead for Tonya. External callers route only to Scout; internal specialist details live only in workspace-research.",
      ancestorTeamIds: [],
      descendantTeamIds: [],
      teamManifest: "/teams/research/workspace-research/agents/research-runtimes.json",
    },
  ],
  k8sCluster: [
    {
      ...k8sDefaults,
      id: "tonya",
      name: "Tonya",
      role: "K8s OpenClaw gateway - primary cloud orchestrator",
      namespace: "agents",
      status: "deployed",
      triggers: ["orchestration", "routing"],
      maxConcurrentSessions: 1,
    },
    {
      ...k8sDefaults,
      id: "2tony",
      name: "2Tony",
      role: "HTTP task executor - canonical POST /task worker ingress",
      namespace: "agents",
      status: "deployed",
      triggers: ["engineering", "infrastructure"],
      maxConcurrentSessions: 1,
      port: 3009,
      replicas: 1,
      endpoints: ["GET /health", "GET /ready", "POST /task", "POST /execute"],
    },
    {
      ...k8sDefaults,
      id: "angela",
      name: "Angela",
      role: "Marketing orchestrator - domain-separated OpenClaw runtime",
      namespace: "agents",
      status: "deployed",
      triggers: ["marketing"],
      maxConcurrentSessions: 1,
    },
    {
      ...k8sDefaults,
      id: "qdrant",
      name: "Qdrant",
      role: "Shared vector DB - StatefulSet, not an agent. Context bus for K8s agents.",
      namespace: "agents",
      status: "deployed",
      triggers: [],
      maxConcurrentSessions: 1,
      port: 6333,
      replicas: null,
      endpoints: [],
    },
    {
      ...k8sDefaults,
      id: "deb-pod",
      name: "Deb (pod)",
      role: "Kanban HTTP service",
      namespace: "agents",
      status: "deployed",
      triggers: ["board", "sprint"],
      maxConcurrentSessions: 1,
      port: 3010,
      endpoints: ["GET /health", "GET /ready", "POST /status", "POST /update"],
    },
  ],
  identities: [
    {
      id: "raekwon",
      kind: "agent",
      name: "Raekwon the Chef",
      role: "Backend - Express 5, Prisma 7, PostgreSQL",
      capabilities: ["backend", "api"],
      teamIds: ["execution-fleet"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "ghostface",
      kind: "agent",
      name: "Ghostface Killah",
      role: "DevOps - K8s, Azure, Docker, GitHub Actions",
      capabilities: ["kubernetes", "aks"],
      teamIds: ["execution-fleet"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "deb",
      kind: "agent",
      name: "Deb",
      role: "GitHub Projects kanban operator",
      capabilities: ["kanban", "board"],
      teamIds: ["project-ops"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "tonys-angels",
      kind: "agent",
      name: "Tony's Angels",
      role: "Marketing orchestrator",
      capabilities: ["marketing", "campaign"],
      teamIds: ["marketing"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "story-architect",
      kind: "agent",
      name: "Story Architect",
      role: "Narrative strategy specialist",
      capabilities: ["positioning", "storytelling", "campaign strategy"],
      teamIds: ["marketing"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "copywriting-ninja",
      kind: "agent",
      name: "Copywriting Ninja",
      role: "High-conversion copy specialist",
      capabilities: [
        "copywriting",
        "conversion optimization",
        "social content",
      ],
      teamIds: ["marketing"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "investor-deck-architect",
      kind: "agent",
      name: "Investor Deck Architect",
      role: "Investor narrative and deck specialist",
      capabilities: [
        "investor narrative",
        "deck architecture",
        "market analysis",
      ],
      teamIds: ["marketing"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "tonya",
      kind: "runtime",
      name: "Tonya",
      role: "K8s OpenClaw gateway - primary cloud orchestrator",
      capabilities: ["orchestration", "routing"],
      teamIds: ["control-plane"],
      leadTeamIds: ["control-plane"],
      maxConcurrentSessions: 1,
    },
    {
      id: "2tony",
      kind: "runtime",
      name: "2Tony",
      role: "HTTP task executor - canonical POST /task worker ingress",
      capabilities: ["engineering", "infrastructure"],
      teamIds: ["execution-fleet"],
      leadTeamIds: ["execution-fleet"],
      maxConcurrentSessions: 1,
    },
    {
      id: "angela",
      kind: "runtime",
      name: "Angela",
      role: "Marketing orchestrator - domain-separated OpenClaw runtime",
      capabilities: ["marketing"],
      teamIds: ["marketing"],
      leadTeamIds: ["marketing"],
      maxConcurrentSessions: 1,
    },
    {
      id: "scout",
      kind: "agent",
      name: "Scout",
      role: "Research lead",
      capabilities: [
        "reconnaissance",
        "file location intelligence",
        "git-aware project indexing",
        "current-state evidence retrieval",
        "source discovery",
        "docs discovery",
        "multi-provider web discovery",
        "community signal retrieval",
        "deep scrape fallback",
        "web search",
        "scout",
        "scout school",
        "evidence retrieval",
        "where is this file",
        "what changed in this repo",
        "current market check",
        "doc discovery",
        "web fetch",
        "upstream openclaw changes",
        "verify current state",
        "Research operations — filesystem cartography, git-aware project indexing, multi-provider web retrieval, and upstream OpenClaw watch synthesis",
      ],
      teamIds: ["control-plane", "research"],
      leadTeamIds: ["research"],
      maxConcurrentSessions: 1,
    },
    {
      id: "sproket",
      kind: "agent",
      name: "Sproket",
      role: "Filesystem cartographer",
      capabilities: [
        "filesystem search",
        "path discovery",
        "repo mapping",
        "git-aware search",
        "filesystem",
        "path",
        "repo map",
        "file search",
        "Filesystem — path discovery, repo-shape mapping, git-aware search, cross-root optimization",
      ],
      teamIds: ["research"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "marlin",
      kind: "agent",
      name: "Marlin",
      role: "Web discovery master",
      capabilities: [
        "web search",
        "query formulation",
        "source verification",
        "multi-provider search",
        "community signal research",
        "deep scrape fallback",
        "web",
        "search",
        "source",
        "Web search — multi-provider search, query formulation, source verification",
      ],
      teamIds: ["research"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "gill",
      kind: "agent",
      name: "Gill",
      role: "Upstream watcher",
      capabilities: [
        "upstream watching",
        "changelog drift",
        "pr movement",
        "adoption packets",
        "upstream",
        "changelog",
        "release",
        "Upstream — OpenClaw releases, changelog drift, PR movement, adoption packets",
      ],
      teamIds: ["research"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "qdrant",
      kind: "runtime",
      name: "Qdrant",
      role: "Shared vector DB - StatefulSet, not an agent. Context bus for K8s agents.",
      capabilities: ["Shared vector DB - StatefulSet, not an agent. Context bus for K8s agents."],
      teamIds: ["control-plane"],
      leadTeamIds: [],
      maxConcurrentSessions: 1,
    },
    {
      id: "deb-pod",
      kind: "runtime",
      name: "Deb (pod)",
      role: "Kanban HTTP service",
      capabilities: ["board", "sprint"],
      teamIds: ["project-ops"],
      leadTeamIds: ["project-ops"],
      maxConcurrentSessions: 1,
    },
  ],
} as unknown as OperatorControlSnapshot["registryDetail"];
