export type GatewayMode = "legacy" | "canonical";

export type SurfaceContract = {
  key: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  canonicalPath: (params?: Record<string, string>) => string;
  legacyPath?: (params?: Record<string, string>) => string;
  classification: "gateway-native" | "compatibility-shim" | "blocked";
  degradation: "hard" | "gap" | "silent";
  owner: string;
  note: string;
};

const p = (params: Record<string, string> | undefined, k: string): string => {
  const v = params?.[k];
  if (!v) throw new Error(`SURFACE_CONTRACTS: missing path param "${k}"`);
  return encodeURIComponent(v);
};

export const SURFACE_CONTRACTS: Record<string, SurfaceContract> = {
  "vault.tree": {
    key: "vault.tree",
    method: "GET",
    legacyPath: () => "/api/obsidian/tree",
    canonicalPath: () => "/api/obsidian/tree",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "vault/gateway owner",
    note: "Obsidian vault tree; no native gateway route identified yet.",
  },
  "vault.read": {
    key: "vault.read",
    method: "GET",
    legacyPath: () => "/api/obsidian/read",
    canonicalPath: () => "/api/obsidian/read",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "vault/gateway owner",
    note: "Obsidian file read; query string appended by caller.",
  },
  "library.fleetStatus": {
    key: "library.fleetStatus",
    method: "GET",
    legacyPath: () => "/library/api/fleet-status",
    canonicalPath: () => "/api/plugins/library/fleet-status",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "library gateway owner",
    note: "Base Sigmund fleet snapshot (cavi-data loadFleetLibraryLive; out of scope to edit).",
  },
  "library.status": {
    key: "library.status",
    method: "GET",
    legacyPath: () => "/library/api/status",
    canonicalPath: () => "/api/plugins/library/status",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "library gateway owner",
    note: "Scholar's Lounge ingest pipeline counters.",
  },
  "library.inbox": {
    key: "library.inbox",
    method: "GET",
    legacyPath: () => "/library/api/inbox",
    canonicalPath: () => "/api/plugins/library/inbox",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "library gateway owner",
    note: "Optional inbox item detail.",
  },
  "library.promotable": {
    key: "library.promotable",
    method: "GET",
    legacyPath: () => "/library/api/promotable",
    canonicalPath: () => "/api/plugins/library/promotable",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "library gateway owner",
    note: "Promotable note rows.",
  },
  "library.reviewRequests": {
    key: "library.reviewRequests",
    method: "GET",
    legacyPath: () => "/library/api/review-requests",
    canonicalPath: () => "/api/plugins/library/review-requests",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "library gateway owner",
    note: "Review-request state joined onto promotable notes.",
  },
  "library.search": {
    key: "library.search",
    method: "GET",
    legacyPath: () => "/library/api/search",
    canonicalPath: () => "/api/plugins/library/search",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "library gateway owner",
    note: "Library search endpoint used as an optional trading workspace enrichment.",
  },
  "portal.dashboard": {
    key: "portal.dashboard",
    method: "GET",
    legacyPath: (params) => `/${p(params, "portal")}/api/dashboard`,
    canonicalPath: (params) => `/api/plugins/portal/${p(params, "portal")}/dashboard`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "portal gateway owner",
    note: "Portal dashboard aggregate (martina/scout/angela/machine).",
  },
  "portal.config": {
    key: "portal.config",
    method: "POST",
    legacyPath: (params) => `/${p(params, "portal")}/api/config`,
    canonicalPath: (params) => `/api/plugins/portal/${p(params, "portal")}/config`,
    classification: "blocked",
    degradation: "hard",
    owner: "portal gateway owner",
    note: "PORTAL_CONFIG_PATCH_V1 write; not implemented gateway-side (apis-needed.md).",
  },
  "gateway.health": {
    key: "gateway.health",
    method: "GET",
    canonicalPath: () => "/health",
    classification: "gateway-native",
    degradation: "hard",
    owner: "method-man",
    note: "Primary reachability check for the selected gateway API server.",
  },
  "gateway.healthDetailed": {
    key: "gateway.healthDetailed",
    method: "GET",
    canonicalPath: () => "/health/detailed",
    classification: "gateway-native",
    degradation: "gap",
    owner: "method-man",
    note: "Detailed gateway health check; absence is a compatibility gap when basic health/capabilities pass.",
  },
  "gateway.capabilities": {
    key: "gateway.capabilities",
    method: "GET",
    canonicalPath: () => "/v1/capabilities",
    classification: "gateway-native",
    degradation: "hard",
    owner: "method-man",
    note: "Authenticated API-server capability proof for saved bearer tokens.",
  },
  "gateway.websocket": {
    key: "gateway.websocket",
    method: "GET",
    canonicalPath: () => "/api/ws",
    classification: "gateway-native",
    degradation: "hard",
    owner: "method-man",
    note: "Dashboard/TUI JSON-RPC websocket path for chat, sessions, logs, and health snapshots.",
  },
  "hermes.runs": {
    key: "hermes.runs",
    method: "POST",
    canonicalPath: () => "/v1/runs",
    classification: "gateway-native",
    degradation: "hard",
    owner: "method-man",
    note: "Hermes REST/SSE run creation endpoint.",
  },
  "kanban.tasks": {
    key: "kanban.tasks",
    method: "POST",
    canonicalPath: () => "/api/plugins/kanban/tasks",
    classification: "gateway-native",
    degradation: "hard",
    owner: "gateway/kanban owner",
    note: "Kanban task creation endpoint for mobile and operator surfaces.",
  },
  "kanban.board": {
    key: "kanban.board",
    method: "GET",
    canonicalPath: () => "/api/plugins/kanban/board",
    classification: "gateway-native",
    degradation: "hard",
    owner: "gateway/kanban owner",
    note: "Unified Kanban board for Deb and Operator visibility.",
  },
  "cavi.costHistory": {
    key: "cavi.costHistory",
    method: "GET",
    legacyPath: () => "/cavi-control/api/cost/history",
    canonicalPath: () => "/api/plugins/cavi-control/cost/history",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Cost history shim; no native gateway cost history endpoint identified.",
  },
  "cavi.deb.root": {
    key: "cavi.deb.root",
    method: "GET",
    legacyPath: () => "/cavi-control/api/deb",
    canonicalPath: () => "/api/plugins/cavi-control/deb",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Deb Project Ops aggregate shim root endpoint.",
  },
  "cavi.deb.profile": {
    key: "cavi.deb.profile",
    method: "GET",
    legacyPath: () => "/cavi-control/api/deb/profile",
    canonicalPath: () => "/api/plugins/cavi-control/deb/profile",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Deb profile snapshot shim endpoint.",
  },
  "cavi.deb.sprint": {
    key: "cavi.deb.sprint",
    method: "GET",
    legacyPath: () => "/cavi-control/api/deb/sprint",
    canonicalPath: () => "/api/plugins/cavi-control/deb/sprint",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Deb sprint board shim endpoint.",
  },
  "cavi.deb.backlog": {
    key: "cavi.deb.backlog",
    method: "GET",
    legacyPath: () => "/cavi-control/api/deb/backlog",
    canonicalPath: () => "/api/plugins/cavi-control/deb/backlog",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Deb backlog listing shim endpoint.",
  },
  "cavi.deb.call": {
    key: "cavi.deb.call",
    method: "POST",
    legacyPath: () => "/cavi-control/api/deb/call",
    canonicalPath: () => "/api/plugins/cavi-control/deb/call",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Deb command/call shim endpoint.",
  },
  "cavi.operator.status": {
    key: "cavi.operator.status",
    method: "GET",
    legacyPath: () => "/cavi-control/api/operator/status",
    canonicalPath: () => "/api/plugins/cavi-control/operator/status",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Legacy operator status fallback used by HTTP preflight.",
  },
  "cavi.operator.snapshot": {
    key: "cavi.operator.snapshot",
    method: "GET",
    legacyPath: () => "/cavi-control/api/operator/snapshot",
    canonicalPath: () => "/api/plugins/cavi-control/operator/snapshot",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Operator aggregate shim preserves the existing CAVI snapshot shape; Kanban board remains a separate native surface.",
  },
  "cavi.operator.tasks": {
    key: "cavi.operator.tasks",
    method: "POST",
    legacyPath: () => "/cavi-control/api/operator/tasks",
    canonicalPath: () => "/api/plugins/kanban/tasks",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "ODB + gateway owner",
    note: "Operator task create shim mapped to Kanban task creation server-side.",
  },
  "cavi.operator.task": {
    key: "cavi.operator.task",
    method: "GET",
    legacyPath: (params) => `/cavi-control/api/operator/tasks/${p(params, "taskId")}`,
    canonicalPath: (params) => `/api/plugins/cavi-control/operator/tasks/${p(params, "taskId")}`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "ODB + gateway owner",
    note: "Operator task read by task id for stable task identity and detail hydration.",
  },
  "cavi.operator.taskDiscourse": {
    key: "cavi.operator.taskDiscourse",
    method: "GET",
    legacyPath: (params) => `/cavi-control/api/operator/tasks/${p(params, "taskId")}/discourse`,
    canonicalPath: (params) => `/api/plugins/cavi-control/operator/tasks/${p(params, "taskId")}/discourse`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "ODB + gateway owner",
    note: "Operator task discourse read for threaded task context.",
  },
  "cavi.operator.registry": {
    key: "cavi.operator.registry",
    method: "GET",
    legacyPath: () => "/cavi-control/api/operator/registry",
    canonicalPath: () => "/api/plugins/cavi-control/operator/registry",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Operator registry roster and capability metadata.",
  },
  "cavi.operator.memory": {
    key: "cavi.operator.memory",
    method: "GET",
    legacyPath: () => "/cavi-control/api/operator/memory",
    canonicalPath: () => "/api/plugins/cavi-control/operator/memory",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Operator memory summary and persisted context traces.",
  },
  "cavi.operator.workerReady": {
    key: "cavi.operator.workerReady",
    method: "GET",
    legacyPath: () => "/cavi-control/api/operator/worker/ready",
    canonicalPath: () => "/api/plugins/cavi-control/operator/worker/ready",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Operator worker readiness snapshot for preflight health.",
  },
  "cavi.operator.workerTasks": {
    key: "cavi.operator.workerTasks",
    method: "GET",
    legacyPath: () => "/cavi-control/api/operator/worker/tasks",
    canonicalPath: () => "/api/plugins/cavi-control/operator/worker/tasks",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "gateway/cavi owner",
    note: "Operator worker task queue/status summary.",
  },
  "frontDoor.dashboard": {
    key: "frontDoor.dashboard",
    method: "GET",
    legacyPath: () => "/front-door/api/dashboard",
    canonicalPath: () => "/api/plugins/front-door/dashboard",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door dashboard shim.",
  },
  "frontDoor.ideaList": {
    key: "frontDoor.ideaList",
    method: "GET",
    legacyPath: () => "/front-door/api/ideas",
    canonicalPath: () => "/api/plugins/front-door/ideas",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door idea list/read shim.",
  },
  "frontDoor.ideaCreate": {
    key: "frontDoor.ideaCreate",
    method: "POST",
    legacyPath: () => "/front-door/api/ideas",
    canonicalPath: () => "/api/plugins/front-door/ideas",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door idea creation shim.",
  },
  "frontDoor.ideaDetail": {
    key: "frontDoor.ideaDetail",
    method: "GET",
    legacyPath: (params) => `/front-door/api/ideas/${p(params, "id")}`,
    canonicalPath: (params) => `/api/plugins/front-door/ideas/${p(params, "id")}`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door idea detail read shim.",
  },
  "frontDoor.ideaPatch": {
    key: "frontDoor.ideaPatch",
    method: "PATCH",
    legacyPath: (params) => `/front-door/api/ideas/${p(params, "id")}`,
    canonicalPath: (params) => `/api/plugins/front-door/ideas/${p(params, "id")}`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door idea detail mutation shim.",
  },
  "frontDoor.ideaPromote": {
    key: "frontDoor.ideaPromote",
    method: "POST",
    legacyPath: (params) => `/front-door/api/ideas/${p(params, "id")}/promote`,
    canonicalPath: (params) => `/api/plugins/front-door/ideas/${p(params, "id")}/promote`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door idea promotion shim.",
  },
  "frontDoor.projectList": {
    key: "frontDoor.projectList",
    method: "GET",
    legacyPath: () => "/front-door/api/projects",
    canonicalPath: () => "/api/plugins/front-door/projects",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door projects list shim.",
  },
  "frontDoor.projectDetail": {
    key: "frontDoor.projectDetail",
    method: "GET",
    legacyPath: (params) => `/front-door/api/projects/${p(params, "id")}`,
    canonicalPath: (params) => `/api/plugins/front-door/projects/${p(params, "id")}`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door project detail shim.",
  },
  "frontDoor.memoryList": {
    key: "frontDoor.memoryList",
    method: "GET",
    legacyPath: () => "/front-door/api/memory",
    canonicalPath: () => "/api/plugins/front-door/memory",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door memory read shim.",
  },
  "frontDoor.memoryCreate": {
    key: "frontDoor.memoryCreate",
    method: "POST",
    legacyPath: () => "/front-door/api/memory",
    canonicalPath: () => "/api/plugins/front-door/memory",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door memory mutation shim.",
  },
  "frontDoor.articleList": {
    key: "frontDoor.articleList",
    method: "GET",
    legacyPath: () => "/front-door/api/articles",
    canonicalPath: () => "/api/plugins/front-door/articles",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door article read shim.",
  },
  "frontDoor.articleCreate": {
    key: "frontDoor.articleCreate",
    method: "POST",
    legacyPath: () => "/front-door/api/articles",
    canonicalPath: () => "/api/plugins/front-door/articles",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door article mutation shim.",
  },
  "frontDoor.inboxUpload": {
    key: "frontDoor.inboxUpload",
    method: "POST",
    legacyPath: () => "/front-door/api/inbox",
    canonicalPath: () => "/api/plugins/front-door/inbox",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Front Door inbox upload shim.",
  },
  "frontDoor.ideas": {
    key: "frontDoor.ideas",
    method: "POST",
    legacyPath: () => "/front-door/api/ideas",
    canonicalPath: () => "/api/plugins/front-door/ideas",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Legacy alias for frontDoor.ideaCreate (kept for web compatibility).",
  },
  "frontDoor.idea": {
    key: "frontDoor.idea",
    method: "PATCH",
    legacyPath: (params) => `/front-door/api/ideas/${p(params, "id")}`,
    canonicalPath: (params) => `/api/plugins/front-door/ideas/${p(params, "id")}`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Legacy alias for frontDoor.ideaPatch (kept for web compatibility).",
  },
  "frontDoor.memory": {
    key: "frontDoor.memory",
    method: "POST",
    legacyPath: () => "/front-door/api/memory",
    canonicalPath: () => "/api/plugins/front-door/memory",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Legacy alias for frontDoor.memoryCreate (kept for web compatibility).",
  },
  "frontDoor.articles": {
    key: "frontDoor.articles",
    method: "POST",
    legacyPath: () => "/front-door/api/articles",
    canonicalPath: () => "/api/plugins/front-door/articles",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Legacy alias for frontDoor.articleCreate (kept for web compatibility).",
  },
  "frontDoor.inbox": {
    key: "frontDoor.inbox",
    method: "POST",
    legacyPath: () => "/front-door/api/inbox",
    canonicalPath: () => "/api/plugins/front-door/inbox",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "front-door gateway owner",
    note: "Legacy alias for frontDoor.inboxUpload (kept for web compatibility).",
  },
  "trading.dashboard": {
    key: "trading.dashboard",
    method: "GET",
    legacyPath: () => "/trading/api/dashboard",
    canonicalPath: () => "/api/plugins/trading/dashboard",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "trading gateway owner",
    note: "Trading workspace dashboard shim.",
  },
  "trading.researchPackets": {
    key: "trading.researchPackets",
    method: "GET",
    legacyPath: () => "/trading/api/research-packets",
    canonicalPath: () => "/api/plugins/trading/research-packets",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "trading gateway owner",
    note: "Trading research packet list shim.",
  },
  "trading.sourceRegistry": {
    key: "trading.sourceRegistry",
    method: "GET",
    legacyPath: () => "/trading/api/source-registry",
    canonicalPath: () => "/api/plugins/trading/source-registry",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "trading gateway owner",
    note: "Trading source registry shim for connector/key gap status.",
  },
  "machine.dashboard": {
    key: "machine.dashboard",
    method: "GET",
    legacyPath: () => "/machine/api/dashboard",
    canonicalPath: () => "/api/plugins/machine/dashboard",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "machine gateway owner",
    note: "Machine portal aggregate dashboard shim.",
  },
  "machine.comedyRun": {
    key: "machine.comedyRun",
    method: "POST",
    legacyPath: () => "/machine/api/comedy/run",
    canonicalPath: () => "/v1/runs",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "machine/chris agent owner",
    note: "Chris comedy action shim with Hermes REST/SSE run fallback.",
  },
  "machine.ttsProviders": {
    key: "machine.ttsProviders",
    method: "GET",
    legacyPath: () => "/machine/api/tts/providers",
    canonicalPath: () => "/api/plugins/machine/tts/providers",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "machine gateway owner",
    note: "Voice Lab provider inventory shim.",
  },
  "machine.tts": {
    key: "machine.tts",
    method: "POST",
    legacyPath: () => "/machine/api/tts",
    canonicalPath: () => "/api/plugins/machine/tts",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "machine gateway owner",
    note: "Machine text-to-speech render shim.",
  },
  "machine.media": {
    key: "machine.media",
    method: "GET",
    legacyPath: (params) => `/machine/api/media?name=${p(params, "filename")}`,
    canonicalPath: (params) => `/api/plugins/machine/media?name=${p(params, "filename")}`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "machine gateway owner",
    note: "Authenticated Machine media fetch/thumbnail shim.",
  },
  "machine.memeJobs": {
    key: "machine.memeJobs",
    method: "GET",
    legacyPath: () => "/machine/api/meme/jobs",
    canonicalPath: () => "/api/plugins/machine/meme/jobs",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "machine gateway owner",
    note: "Machine meme job listing/mutation shim.",
  },
  "machine.inbox": {
    key: "machine.inbox",
    method: "POST",
    legacyPath: () => "/machine/api/inbox",
    canonicalPath: () => "/api/plugins/machine/inbox",
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "machine gateway owner",
    note: "Machine media/action inbox upload shim.",
  },
  "portalMemory.snapshot": {
    key: "portalMemory.snapshot",
    method: "GET",
    legacyPath: (params) =>
      `/cavi-control/api/portal-memory/teams/${p(params, "teamSlug")}/members/${p(params, "memberId")}/${p(params, "memoryKey")}`,
    canonicalPath: (params) =>
      `/api/plugins/portal-memory/teams/${p(params, "teamSlug")}/members/${p(params, "memberId")}/${p(params, "memoryKey")}`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "machine gateway owner",
    note: "Portal-memory snapshot shim for specialist room state.",
  },
  "martina.artifactPreview": {
    key: "martina.artifactPreview",
    method: "GET",
    legacyPath: (params) =>
      `/martina/api/artifacts/${p(params, "bucket")}/${p(params, "name")}/preview`,
    canonicalPath: (params) =>
      `/api/plugins/portal/martina/artifacts/${p(params, "bucket")}/${p(params, "name")}/preview`,
    classification: "compatibility-shim",
    degradation: "gap",
    owner: "martina gateway owner",
    note: "Martina artifact preview shim.",
  },
  "wuTang.githubProxy": {
    key: "wuTang.githubProxy",
    method: "GET",
    legacyPath: () => "/cavi-control/api/wu-tang/github",
    canonicalPath: () => "/api/plugins/wu-tang/github",
    classification: "compatibility-shim",
    degradation: "hard",
    owner: "wu-tang gateway owner",
    note: "Wu-Tang GitHub proxy prefix; server keeps PAT custody.",
  },
  "wuTang.githubProxyWildcard": {
    key: "wuTang.githubProxyWildcard",
    method: "GET",
    legacyPath: () => "/cavi-control/api/wu-tang/github/*",
    canonicalPath: () => "/api/plugins/wu-tang/github/*",
    classification: "compatibility-shim",
    degradation: "hard",
    owner: "wu-tang gateway owner",
    note: "Wu-Tang GitHub proxy route pattern for contract ledger display.",
  },
};
