import type { SurfaceContract } from "../../../contracts/surfaces.js";
import { CAVI_CONTROL_OPERATOR_API } from "./paths.js";

export type { SurfaceContract };

const p = (params: Record<string, string> | undefined, k: string): string => {
  const v = params?.[k];
  if (!v) throw new Error(`CAVI_SURFACE_CONTRACTS: missing path param "${k}"`);
  return encodeURIComponent(v);
};

const raw = (params: Record<string, string> | undefined, k: string): string => {
  const v = params?.[k];
  if (!v) throw new Error(`CAVI_SURFACE_CONTRACTS: missing path param "${k}"`);
  return v;
};

export const CAVI_SURFACE_CONTRACTS: Record<string, SurfaceContract> = {
  "library.fleetStatus": {
    key: "library.fleetStatus",
    method: "GET",
    path: () => "/api/plugins/library/fleet-status",
    degradation: "gap",
    owner: "extensions/cavi/library",
    note: "Fleet library status extension endpoint.",
  },
  "library.status": {
    key: "library.status",
    method: "GET",
    path: () => "/api/plugins/library/status",
    degradation: "gap",
    owner: "extensions/cavi/library",
    note: "Library ingest pipeline counters.",
  },
  "library.inbox": {
    key: "library.inbox",
    method: "GET",
    path: () => "/api/plugins/library/inbox",
    degradation: "gap",
    owner: "extensions/cavi/library",
    note: "Library inbox endpoint.",
  },
  "library.promotable": {
    key: "library.promotable",
    method: "GET",
    path: () => "/api/plugins/library/promotable",
    degradation: "gap",
    owner: "extensions/cavi/library",
    note: "Promotable library rows.",
  },
  "library.reviewRequests": {
    key: "library.reviewRequests",
    method: "GET",
    path: () => "/api/plugins/library/review-requests",
    degradation: "gap",
    owner: "extensions/cavi/library",
    note: "Library review-request rows.",
  },
  "library.search": {
    key: "library.search",
    method: "GET",
    path: () => "/api/plugins/library/search",
    degradation: "gap",
    owner: "extensions/cavi/library",
    note: "Library search endpoint.",
  },
  "library.clip": {
    key: "library.clip",
    method: "POST",
    path: () => "/api/plugins/library/clip",
    degradation: "gap",
    owner: "extensions/cavi/library",
    note: "CaviClip ingest endpoint (URL/text/manual-file capture into the library intake).",
  },
  "portal.dashboard": {
    key: "portal.dashboard",
    method: "GET",
    path: (params) => `/api/plugins/portal/${p(params, "portal")}/dashboard`,
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal dashboard aggregate.",
  },
  "portal.config": {
    key: "portal.config",
    method: "POST",
    path: (params) => `/api/plugins/portal/${p(params, "portal")}/config`,
    degradation: "hard",
    owner: "extensions/cavi/portal",
    note: "Portal config patch endpoint.",
  },
  "cavi.costHistory": {
    key: "cavi.costHistory",
    method: "GET",
    path: () => "/api/plugins/cavi-control/cost/history",
    degradation: "gap",
    owner: "extensions/cavi",
    note: "CAVI cost history extension endpoint.",
  },
  "cavi.projectBoard.root": {
    key: "cavi.projectBoard.root",
    method: "GET",
    path: () => "/api/plugins/cavi-control/kanban",
    degradation: "gap",
    owner: "extensions/cavi/project-board",
    note: "Project Board aggregate endpoint.",
  },
  "cavi.projectBoard.profile": {
    key: "cavi.projectBoard.profile",
    method: "GET",
    path: () => "/api/plugins/cavi-control/kanban/profile",
    degradation: "gap",
    owner: "extensions/cavi/project-board",
    note: "Project Board profile endpoint.",
  },
  "cavi.projectBoard.sprint": {
    key: "cavi.projectBoard.sprint",
    method: "GET",
    path: () => "/api/plugins/cavi-control/kanban/sprint",
    degradation: "gap",
    owner: "extensions/cavi/project-board",
    note: "Project Board sprint endpoint.",
  },
  "cavi.projectBoard.backlog": {
    key: "cavi.projectBoard.backlog",
    method: "GET",
    path: () => "/api/plugins/cavi-control/kanban/backlog",
    degradation: "gap",
    owner: "extensions/cavi/project-board",
    note: "Project Board backlog endpoint.",
  },
  "cavi.projectBoard.call": {
    key: "cavi.projectBoard.call",
    method: "POST",
    path: () => "/api/plugins/cavi-control/kanban/call",
    degradation: "gap",
    owner: "extensions/cavi/project-board",
    note: "Project Board command endpoint.",
  },
  "cavi.operator.status": {
    key: "cavi.operator.status",
    method: "GET",
    path: () => CAVI_CONTROL_OPERATOR_API.status,
    degradation: "gap",
    owner: "extensions/cavi/operator-control",
    note: "CAVI Control operator status endpoint.",
  },
  "cavi.operator.snapshot": {
    key: "cavi.operator.snapshot",
    method: "GET",
    path: () => CAVI_CONTROL_OPERATOR_API.snapshot,
    degradation: "gap",
    owner: "extensions/cavi/operator-control",
    note: "CAVI Control operator aggregate snapshot endpoint.",
  },
  "cavi.operator.tasks": {
    key: "cavi.operator.tasks",
    method: "POST",
    path: () => CAVI_CONTROL_OPERATOR_API.tasks,
    degradation: "gap",
    owner: "extensions/cavi/operator-control",
    note: "CAVI Control operator task create endpoint.",
  },
  "cavi.operator.task": {
    key: "cavi.operator.task",
    method: "GET",
    path: (params) => CAVI_CONTROL_OPERATOR_API.task(raw(params, "taskId")),
    degradation: "gap",
    owner: "extensions/cavi/operator-control",
    note: "CAVI Control operator task detail endpoint.",
  },
  "cavi.operator.taskDiscourse": {
    key: "cavi.operator.taskDiscourse",
    method: "GET",
    path: (params) =>
      CAVI_CONTROL_OPERATOR_API.taskDiscourse(raw(params, "taskId")),
    degradation: "gap",
    owner: "extensions/cavi/discourse",
    note: "CAVI Control operator task discourse endpoint.",
  },
  "cavi.operator.registry": {
    key: "cavi.operator.registry",
    method: "GET",
    path: () => CAVI_CONTROL_OPERATOR_API.registry,
    degradation: "gap",
    owner: "extensions/cavi/operator-control",
    note: "CAVI Control operator registry endpoint.",
  },
  "cavi.operator.memory": {
    key: "cavi.operator.memory",
    method: "GET",
    path: () => CAVI_CONTROL_OPERATOR_API.memory,
    degradation: "gap",
    owner: "extensions/cavi/operator-control",
    note: "CAVI Control operator memory endpoint.",
  },
  "cavi.operator.workerReady": {
    key: "cavi.operator.workerReady",
    method: "GET",
    path: () => CAVI_CONTROL_OPERATOR_API.workerReady,
    degradation: "gap",
    owner: "extensions/cavi/operator-control",
    note: "CAVI Control operator worker readiness endpoint.",
  },
  "cavi.operator.workerTasks": {
    key: "cavi.operator.workerTasks",
    method: "GET",
    path: () => CAVI_CONTROL_OPERATOR_API.workerTasks,
    degradation: "gap",
    owner: "extensions/cavi/operator-control",
    note: "CAVI Control operator worker task queue endpoint.",
  },
  "frontDoor.dashboard": {
    key: "frontDoor.dashboard",
    method: "GET",
    path: () => "/api/plugins/front-door/dashboard",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door dashboard endpoint.",
  },
  "frontDoor.ideas": {
    key: "frontDoor.ideas",
    method: "POST",
    path: () => "/api/plugins/front-door/ideas",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door idea creation endpoint.",
  },
  "frontDoor.memory": {
    key: "frontDoor.memory",
    method: "POST",
    path: () => "/api/plugins/front-door/memory",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door memory endpoint.",
  },
  "frontDoor.articles": {
    key: "frontDoor.articles",
    method: "POST",
    path: () => "/api/plugins/front-door/articles",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door article endpoint.",
  },
  "frontDoor.inbox": {
    key: "frontDoor.inbox",
    method: "POST",
    path: () => "/api/plugins/front-door/inbox",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door inbox endpoint.",
  },
  "trading.dashboard": {
    key: "trading.dashboard",
    method: "GET",
    path: () => "/api/plugins/trading/dashboard",
    degradation: "gap",
    owner: "extensions/cavi/trading",
    note: "Trading workspace dashboard endpoint.",
  },
  "trading.researchPackets": {
    key: "trading.researchPackets",
    method: "GET",
    path: () => "/api/plugins/trading/research-packets",
    degradation: "gap",
    owner: "extensions/cavi/trading",
    note: "Trading research packet endpoint.",
  },
  "machine.dashboard": {
    key: "machine.dashboard",
    method: "GET",
    path: () => "/api/plugins/machine/dashboard",
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal media dashboard endpoint.",
  },
  "machine.comedyRun": {
    key: "machine.comedyRun",
    method: "POST",
    path: () => "/v1/runs",
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal action route with gateway run fallback.",
  },
  "machine.ttsProviders": {
    key: "machine.ttsProviders",
    method: "GET",
    path: () => "/api/plugins/machine/tts/providers",
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal TTS provider inventory.",
  },
  "machine.tts": {
    key: "machine.tts",
    method: "POST",
    path: () => "/api/plugins/machine/tts",
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal TTS render endpoint.",
  },
  "machine.media": {
    key: "machine.media",
    method: "GET",
    path: (params) =>
      `/api/plugins/machine/media?name=${p(params, "filename")}`,
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal media fetch endpoint.",
  },
  "machine.memeJobs": {
    key: "machine.memeJobs",
    method: "GET",
    path: () => "/api/plugins/machine/meme/jobs",
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal meme job endpoint.",
  },
  "machine.inbox": {
    key: "machine.inbox",
    method: "POST",
    path: () => "/api/plugins/machine/inbox",
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal inbox endpoint.",
  },
  "portalMemory.snapshot": {
    key: "portalMemory.snapshot",
    method: "GET",
    path: (params) =>
      `/api/plugins/portal-memory/teams/${p(params, "teamSlug")}/members/${p(params, "memberId")}/${p(params, "memoryKey")}`,
    degradation: "gap",
    owner: "extensions/cavi/portal-memory",
    note: "Portal memory snapshot endpoint.",
  },
  "martina.artifactPreview": {
    key: "martina.artifactPreview",
    method: "GET",
    path: (params) =>
      `/api/plugins/portal/martina/artifacts/${p(params, "bucket")}/${p(params, "name")}/preview`,
    degradation: "gap",
    owner: "extensions/cavi/portal",
    note: "Portal artifact preview endpoint.",
  },
  "wuTang.githubProxyWildcard": {
    key: "wuTang.githubProxyWildcard",
    method: "GET",
    path: () => "/api/plugins/wu-tang/github/*",
    degradation: "hard",
    owner: "extensions/cavi/github-proxy",
    note: "GitHub proxy route pattern.",
  },
};

Object.assign(CAVI_SURFACE_CONTRACTS, {
  "frontDoor.ideaList": {
    key: "frontDoor.ideaList",
    method: "GET",
    path: () => "/api/plugins/front-door/ideas",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door idea list endpoint.",
  },
  "frontDoor.ideaCreate": {
    key: "frontDoor.ideaCreate",
    method: "POST",
    path: () => "/api/plugins/front-door/ideas",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door idea creation endpoint.",
  },
  "frontDoor.ideaDetail": {
    key: "frontDoor.ideaDetail",
    method: "GET",
    path: (params) => `/api/plugins/front-door/ideas/${p(params, "id")}`,
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door idea detail endpoint.",
  },
  "frontDoor.ideaPatch": {
    key: "frontDoor.ideaPatch",
    method: "PATCH",
    path: (params) => `/api/plugins/front-door/ideas/${p(params, "id")}`,
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door idea patch endpoint.",
  },
  "frontDoor.ideaPromote": {
    key: "frontDoor.ideaPromote",
    method: "POST",
    path: (params) =>
      `/api/plugins/front-door/ideas/${p(params, "id")}/promote`,
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door idea promotion endpoint.",
  },
  "frontDoor.projectList": {
    key: "frontDoor.projectList",
    method: "GET",
    path: () => "/api/plugins/front-door/projects",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door project list endpoint.",
  },
  "frontDoor.projectDetail": {
    key: "frontDoor.projectDetail",
    method: "GET",
    path: (params) =>
      `/api/plugins/front-door/projects/${p(params, "id")}`,
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door project detail endpoint.",
  },
  "frontDoor.articleList": {
    key: "frontDoor.articleList",
    method: "GET",
    path: () => "/api/plugins/front-door/articles",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door article list endpoint.",
  },
  "frontDoor.articleCreate": {
    key: "frontDoor.articleCreate",
    method: "POST",
    path: () => "/api/plugins/front-door/articles",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door article creation endpoint.",
  },
  "frontDoor.memoryList": {
    key: "frontDoor.memoryList",
    method: "GET",
    path: () => "/api/plugins/front-door/memory",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door memory list endpoint.",
  },
  "frontDoor.memoryCreate": {
    key: "frontDoor.memoryCreate",
    method: "POST",
    path: () => "/api/plugins/front-door/memory",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door memory creation endpoint.",
  },
  "frontDoor.inboxUpload": {
    key: "frontDoor.inboxUpload",
    method: "POST",
    path: () => "/api/plugins/front-door/inbox",
    degradation: "gap",
    owner: "extensions/cavi/front-door",
    note: "Front Door inbox upload endpoint.",
  },
  "trading.sourceRegistry": {
    key: "trading.sourceRegistry",
    method: "GET",
    path: () => "/api/plugins/trading/source-registry",
    degradation: "gap",
    owner: "extensions/cavi/trading",
    note: "Trading source registry endpoint.",
  },
} satisfies Record<string, SurfaceContract>);

export const SURFACE_CONTRACTS = CAVI_SURFACE_CONTRACTS;
