import type { FleetLibrarySnapshot } from "../../domain/index.js";

export const fallbackFleetLibrary: FleetLibrarySnapshot = {
  generatedAt: Date.now(),
  teams: [
    {
      teamId: "angels",
      teamName: "Angels",
      lead: "service-operator",
      inboxCount: 0,
      candidatesCount: 0,
      promotedCount: 0,
      rejectedCount: 0,
      recentPromotions: [],
      qmdHealth: { lastIndexedAt: null, collectionSize: 0, healthy: true },
    },
    {
      teamId: "research-team",
      teamName: "research team",
      lead: "research-operator",
      inboxCount: 3,
      candidatesCount: 2,
      promotedCount: 8,
      rejectedCount: 1,
      recentPromotions: [
        {
          id: "note_70a1bc23def45678",
          title: "OpenClaw Architecture Deep Dive",
          note_type: "source",
          promoted_at: "2026-04-09T14:30:00Z",
          promoted_by: "research-operator",
        },
      ],
      qmdHealth: { lastIndexedAt: Date.now() - 600_000, collectionSize: 8, healthy: true },
    },
    {
      teamId: "team-gamma",
      teamName: "Griselda",
      lead: "portal-media",
      inboxCount: 2,
      candidatesCount: 3,
      promotedCount: 5,
      rejectedCount: 1,
      recentPromotions: [
        {
          id: "note_69d8de74aeef5a44",
          title: "Truth Serum Comedy Bible",
          note_type: "concept",
          promoted_at: "2026-04-10T00:00:00Z",
          promoted_by: "portal-media",
        },
        {
          id: "note_69d8de746135a5a5",
          title: "Seed Corpus Policy",
          note_type: "concept",
          promoted_at: "2026-04-10T00:00:00Z",
          promoted_by: "portal-media",
        },
      ],
      qmdHealth: { lastIndexedAt: Date.now() - 300_000, collectionSize: 5, healthy: true },
    },
    {
      teamId: "team-delta",
      teamName: "Headhunter",
      lead: "portal-alpha",
      inboxCount: 0,
      candidatesCount: 0,
      promotedCount: 0,
      rejectedCount: 0,
      recentPromotions: [],
      qmdHealth: { lastIndexedAt: null, collectionSize: 0, healthy: true },
    },
    {
      teamId: "team-alpha",
      teamName: "Wu-Tang",
      lead: "operator-a",
      inboxCount: 0,
      candidatesCount: 0,
      promotedCount: 0,
      rejectedCount: 0,
      recentPromotions: [],
      qmdHealth: { lastIndexedAt: null, collectionSize: 0, healthy: true },
    },
    {
      teamId: "team-beta",
      teamName: "Run-DMC",
      lead: "reverend-run",
      inboxCount: 0,
      candidatesCount: 0,
      promotedCount: 0,
      rejectedCount: 0,
      recentPromotions: [],
      qmdHealth: { lastIndexedAt: null, collectionSize: 0, healthy: true },
    },
    {
      teamId: "project-ops",
      teamName: "Paw & Order",
      lead: "project-board",
      inboxCount: 0,
      candidatesCount: 0,
      promotedCount: 0,
      rejectedCount: 0,
      recentPromotions: [],
      qmdHealth: { lastIndexedAt: null, collectionSize: 0, healthy: true },
    },
  ],
  sigmund: {
    status: "online",
    lastIngestAt: Date.now() - 120_000,
    totalProcessed: 14,
  },
};
